data_path: "/glade/scratch/dgagne/track_data_ncar_wrfrt_2020_3km_REFL_COM_ws_nc"
patch_radius: 16
input_variables: ["REFL_COM_curr"]
output_variables: ["HAIL_MAXK1_curr"]
meta_variables: ["masks", "i", "j", "time", "centroid_lon", "centroid_lat",
                 "centroid_i", "centroid_j", "track_id", "track_step", "run_date"]
train_start_date: "2020-04-01"
train_end_date: "2020-05-31"
val_start_date: "2020-06-01"
val_end_date: "2020-06-30"
test_start_date: "2020-07-01"
test_end_date: "2020-07-31"
out_path: "/glade/work/ggantos/mode_cnn_mh_200918/"
classifier: 1
classifier_threshold: 0.04
plot_kwargs:
  REFL_COM_curr:
    vmin: 0
    vmax: 80
    cmap: "gist_ncar"

models:
  cnn_20200504_000:
    min_filters: 16
    filter_width: 5
    filter_growth_rate: 2
    pooling_width: 2
    min_data_width: 4
    output_type: "sigmoid"
    pooling: "mean"
    loss: "binary_crossentropy"
    hidden_activation: "leaky"
    learning_rate: 0.001
    batch_size: 256
    use_dropout: 1
    dropout_alpha: 0.2
    epochs: 20
    dense_neurons: 9
    l2_alpha: 0.001
    early_stopping: 0
    verbose: 1
  cnn_20200504_001:
    min_filters: 16
    filter_width: 5
    filter_growth_rate: 2
    pooling_width: 2
    min_data_width: 4
    output_type: "sigmoid"
    pooling: "mean"
    loss: "binary_crossentropy"
    hidden_activation: "leaky"
    learning_rate: 0.001
    batch_size: 256
    use_dropout: 1
    dropout_alpha: 0.5
    epochs: 20
    dense_neurons: 9
    l2_alpha: 0.001
    early_stopping: 0
    verbose: 1
  cnn_20200504_002:
    min_filters: 16
    filter_width: 5
    filter_growth_rate: 2
    pooling_width: 2
    min_data_width: 4
    output_type: "sigmoid"
    pooling: "mean"
    loss: "binary_crossentropy"
    hidden_activation: "leaky"
    learning_rate: 0.001
    batch_size: 256
    epochs: 20
    dense_neurons: 9
    l2_alpha: 0.001
    early_stopping: 0
    verbose: 1
  cnn_20200504_003:
    min_filters: 16
    filter_width: 5
    filter_growth_rate: 2
    pooling_width: 2
    min_data_width: 4
    output_type: "sigmoid"
    pooling: "mean"
    loss: "binary_crossentropy"
    hidden_activation: "leaky"
    learning_rate: 0.001
    batch_size: 256
    use_dropout: 1
    dropout_alpha: 0.2
    epochs: 20
    dense_neurons: 18
    l2_alpha: 0.001
    early_stopping: 0
    verbose: 1
  cnn_20200504_004:
    min_filters: 16
    filter_width: 5
    filter_growth_rate: 2
    pooling_width: 2
    min_data_width: 8
    output_type: "sigmoid"
    pooling: "mean"
    loss: "binary_crossentropy"
    hidden_activation: "leaky"
    learning_rate: 0.001
    batch_size: 256
    use_dropout: 1
    dropout_alpha: 0.2
    epochs: 20
    dense_neurons: 9
    l2_alpha: 0.001
    early_stopping: 0
    verbose: 1



